version: '3.8'

services:
  filter-service:
    build:
      context: .
      dockerfile: ./filter-service/Dockerfile
    depends_on:
      - postgres-filter
    ports:
      - "8081:8081"
    networks:
      - htt_server_network
  postgres-filter:
    image: postgres:16.4
    container_name: postgres-filter
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fservice
      POSTGRES_DB: fservice_db
      POSTGRES_PORT: 5433  
    command: ["postgres", "-p", "5433"]  
    volumes:
      - ./postgresf-data:/var/lib/postgresql/data  
    ports:
      - "15433:5433"
    networks:
      - htt_server_network

  postgres-processor:
    image: postgres:16.4
    container_name: postgres-processor
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pservice
      POSTGRES_DB: pservice_db
      POSTGRES_PORT: 5434
    command: ["postgres", "-p", "5434"]  
    volumes:
      - ./postgresp-data:/var/lib/postgresql/data  
    ports:
      - "15434:5434"
    networks:
      - htt_server_network
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # ports:
    #   - "19090:9090"
    networks:
      - htt_server_network
  nginx:
    image: nginx:alpine
    ports:
      - "19090:19090"  # Проброс порта на хост
    volumes:
      - .\\nginx-auth\\nginx\\conf\\nginx.conf:/etc/nginx/nginx.conf:ro
      - .\\nginx-auth\\nginx\\conf\\.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - prometheus
    networks:
      - htt_server_network

networks:
  htt_server_network:
    name: htt_network
    driver: bridge