version: '3.8'

services:
  postgres-filter:
    image: postgres:16.4
    container_name: postgres-filter
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fservice
      POSTGRES_DB: fservice_db  
      POSTGRES_PORT: 5433       
    command: postgres -p 5433  
    volumes: 
      - ./postgresf-data:/data/postgresf 
    ports:
      - "15433:5433"

  postgres-processor:
    container_name: postgres-processor
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pservice
      POSTGRES_DB: pservice_db  # Явно задаём имя БД
      POSTGRES_PORT: 5434  
      command: postgres -p 5434
    volumes: 
      - ./postgresp-data:/data/postgresp
    ports:
      - "15434:5434"
    networks: 
      - htt_server_network

networks:
  htt_server_network:
    name: htt_network  # Явное имя для сети
    driver: bridge