global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "filter-service"
    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["filter-service:8082"]

  # - job_name: "processor-service"
  #   scrape_interval: 15s
  #   scrape_timeout: 15s

  #   static_configs:
  #     - targets: ["processor-service:18083"]
